# Generated by Django 2.0.5 on 2018-05-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20180526_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Odate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Bdate',
            field=models.IntegerField(null=True),
        ),
    ]
