# Generated by Django 2.0.5 on 2018-05-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_auto_20180526_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Partname',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
