# Generated by Django 2.0.5 on 2018-05-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Price', models.IntegerField(null=True)),
                ('Kind', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Price', models.IntegerField(null=True)),
                ('Kind', models.CharField(max_length=20)),
                ('HotorIce', models.CharField(choices=[('H', 'Hot'), ('I', 'Ice')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Price', models.IntegerField(null=True)),
                ('Kind', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=20)),
                ('Odate', models.DateTimeField(blank=True, null=True)),
                ('Price', models.IntegerField(null=True)),
                ('Details', models.CharField(max_length=200)),
                ('stats', models.CharField(choices=[('A', 'Accept'), ('P', 'Prepare'), ('C', 'Complete')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Price', models.IntegerField(null=True)),
                ('Kind', models.CharField(max_length=20)),
                ('HotorIce', models.CharField(choices=[('H', 'Hot'), ('I', 'Ice')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Bdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Partname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Phonenumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Username',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='isCaptain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Passwd',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
