# Generated by Django 2.0.5 on 2018-05-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20180526_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Odate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Bdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
