# Generated by Django 2.0.5 on 2018-05-26 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_auto_20180526_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.User'),
        ),
    ]
